version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/mern_auth?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=24h
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local